<?php

/**
 * Dan Cardin (yooper)
 * pulls the top 10 words from tom sawyer and produces are chart
 * require the Composer autoloader 
 */
require_once('vendor/autoload.php');
//used to generate a chart from the output of PHP Text Analysis
require_once('utils/BarPageBuilder.php');
/**
 *  Get some text from the internet
 *  we will grab tom sawyer from the gutenberg project
 *  http://www.gutenberg.org/cache/epub/74/pg74.txt
 * 
 */

/**
 * @var string $book 
 */
$book = file_get_contents('data/books/pg74.txt');


/**
 *  Create a tokenizer object to parse the book into a set of tokens
 *  
 */
$tokenizer = new \TextAnalysis\Tokenizers\GeneralTokenizer();

/**
 * Get the set of tokens generated by the tokenize, see 
 *  
 */
$tokens = $tokenizer->tokenize($book);

$freqDist = new \TextAnalysis\Analysis\FreqDist($tokens);

/**
 * Get the top 10 most used words in Tom Sawyer 
 */
$top10 = array_splice($freqDist->getKeyValuesByFrequency(), 0, 10);


/** 
 * Use High Charts to visualize the data
 */
$pageBuilder = new BarPageBuilder($top10);

$html = $pageBuilder->getHtmlPage();

file_put_contents("pub/pages/example_01_frequency_analysis.html", $html);

echo 'go to the directory pub/pages/example_01_frequency_analysis.html and open the file with your web browser'.PHP_EOL;
/**
 *  go to the directory in this project and open the file with your web browser
 */


